import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

import './globals.css';
import { LoadingProvider } from '../context/loadingContext';
import { Loading } from '../components/ui/loading';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  icons: {
    icon: 'https://conexean-visual-identity.s3.us-east-1.amazonaws.com/favicon.ico',
  },
  title: 'Conexean Default Project',
  description: 'Generated by Conexean CLI',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} antialiased`}>
        <LoadingProvider>
          <Loading />
          {children}
        </LoadingProvider>
      </body>
    </html>
  );
}
